### ISSUE TITLE
Meme Contest

### ISSUE THREAD

**Issue by crisgarner** [cryptexfinance/community-coordination#1]
Create a Meme Contest where participants can submit their favorite CTX / Cryptex Meme.

- [ ] Define rules
- [ ] Define prize
- [ ] Define dates

**Comment by RaphizZGithub** [comment]
I'll handle the Meme Contest next week : 
- Post about the upcoming Meme Contest on the TCAP sub
- Give 1 week (maybe more) for contestants to submit their meme as a link in the comments
- Rewards for the Top 3 best Meme according to the community (either in terms of Upvote or we could make a vote on the discord to draw people to it --> option 2 seems better) 
- Rewards paid on ETH wallet in CTX or TCAP
