### ISSUE TITLE
Community Content on Reddit

### ISSUE THREAD

**Issue by brendan3005** [cryptexfinance/community-coordination#20]
A place to discuss and share ideas on growing Cryptex and TCAP on Reddit - r/totalcryptomarketcap

**Comment by brendan3005** [comment]
Community Content to be generated on Reddit that informs and educates DeFi users about Cryptex and TCAP. I've noticed [r/DeFi](https://www.reddit.com/r/defi/) has become increasingly popular as it limits posts to longform text-only posts. Here's an [example](https://www.reddit.com/r/defi/comments/nj49pi/bridge_stablecoins_to_polygonmatic_while_avoiding/). To our community authors, what kind of quality posts can we make here?

**Comment by RaphizZGithub** [comment]
Kind of content : 
- Weekly Recaps (ongoing)
- Articles about CTX and TCAP being supported by exchanges and DAOs (this gets lots of engagment)
- Posts on various cryptocurrency subs about the ability to invest in the Whole Crypto Market / Investment strategy involving TCAP
- Meme submission on TCAP or CTX

**Comment by tommatzgithub** [comment]
- [ ] Weekly Recaps (ongoing)
- [ ] Articles about CTX and TCAP being suppirted by exchanges and DAOs (this gets lots of engagment)
- [ ] Posts on various cryptocurrency subs about the ability to invest in the Whole Crypto Market / Investment strategy involving TCAP
- [ ] Meme submission on TCAP or CTX
