### ISSUE TITLE
DeBank Listing

### ISSUE THREAD

**Issue by matz0x** [cryptexfinance/community-coordination#23]

**Comment by matz0x** [comment]
lc from the community created the posting https://debank.com/vote/886

Now we need to rally more votes/wallets for it.

**Comment by LeoHChen** [comment]
would love to lead the vote.

**Comment by matz0x** [comment]
Making some progress, have double digit upvotes & monies. Their brand account on Twitter acknowleded our request and is getting to it.

**Comment by LeoHChen** [comment]
just pinged the team in tg channel again.

**Comment by LeoHChen** [comment]
it is done.  debank.com supports cryptex now. so we can close this ticket. @tommatzgithub
