### ISSUE TITLE
Getting TCAP Oracle as Benchmark on Zerion/Coinstats

### ISSUE THREAD

**Issue by ghost** [cryptexfinance/community-coordination#41]

**Comment by matz0x** [comment]
What do you think about adding Zapper to the list?

**Comment by 0x-meta** [comment]
> What do you think about adding Zapper to the list?

Zapper doesn't offer charts for portfolio performance, which is why I didn't include them. I'll keep an eye out for any changes

**Comment by matz0x** [comment]
meta, if you can lead the efforts for this on Coinstats, that would be amazing. Once we get it on coinstats, we can use it to then pitch Zerion (One of our community members can help to get it in front of them).

**Comment by 0x-meta** [comment]
> meta, if you can lead the efforts for this on Coinstats, that would be amazing. Once we get it on coinstats, we can use it to then pitch Zerion (One of our community members can help to get it in front of them).

Sure, I'll see what I can do. Zerion was responsive to my initial inquiry on this already, but we'd need to prioritize it before they update their portfolio dashboard.
